<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>a1f9de63-9a28-4f36-aa27-4433b6dc2f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.filters > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'All')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6658e15-e7d8-45c5-bbde-5a0fda31b115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { selected: showMode() == 'all' }</value>
      <webElementGuid>d1ba2eaf-81ce-423d-8849-cc20a6024526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/all</value>
      <webElementGuid>0213a97d-20d5-48cb-9b6f-9f4ba7f35527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>048409fc-bf8c-4213-8f4b-aefbd1ad5ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;learn-bar&quot;]/section[@class=&quot;todoapp&quot;]/footer[@class=&quot;footer&quot;]/ul[@class=&quot;filters&quot;]/li[1]/a[1]</value>
      <webElementGuid>3ec788f3-fe14-47db-8e84-ba7301c321f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All')]</value>
      <webElementGuid>f4255e87-242f-49e6-a6a1-85dbae384cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items'])[1]/following::a[1]</value>
      <webElementGuid>c153fdc9-ffb7-49d5-9fb3-252bd61867a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>8d187290-2df1-4c37-a83b-179f5446da36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/preceding::a[2]</value>
      <webElementGuid>9876a2ec-bcff-4481-9065-83fd8fb5c62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>55c60e65-63ac-4ffd-bd59-d02ae400b2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/all')]</value>
      <webElementGuid>d960dddc-1591-421f-9eb6-618510c1b88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/ul/li/a</value>
      <webElementGuid>04d3efca-e6f5-44fd-9b31-e5f2758681fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/all' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>d8f254c1-ed52-45bc-8a45-f256f4b67b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
