<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cuci piring_destroy</name>
   <tag></tag>
   <elementGuidId>d8217928-b414-4c89-98ca-bee4fffa08ef</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[1]/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;learn-bar&quot;]/section[@class=&quot;todoapp&quot;]/section[@class=&quot;main&quot;]/ul[@class=&quot;todo-list&quot;]/li[1]/div[@class=&quot;view&quot;]/button[@class=&quot;destroy&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.destroy</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0281e13-49c4-441d-b39c-74ea19d5c085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>destroy</value>
      <webElementGuid>f7c8f8c9-dded-45a8-9e6f-51d933ee63d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: $root.remove</value>
      <webElementGuid>48b7e278-4398-4baf-8059-a6f9332aef5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;learn-bar&quot;]/section[@class=&quot;todoapp&quot;]/section[@class=&quot;main&quot;]/ul[@class=&quot;todo-list&quot;]/li[1]/div[@class=&quot;view&quot;]/button[@class=&quot;destroy&quot;]</value>
      <webElementGuid>72608440-7dc7-4b57-9971-08de16ad0fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[1]/div/button</value>
      <webElementGuid>94f490a0-700f-4bbb-a3c9-a97d1d2b2e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
